on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: commoninteliregistry.azurecr.io
        username: ${{ secrets.acr_commoninteliregistry_username }}
        password: ${{ secrets.acr_commoninteliregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t commoninteliregistry.azurecr.io/commonaks:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push commoninteliregistry.azurecr.io/commonaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_commonaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep common-apps | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace common-apps`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: common-apps
        container-registry-url: commoninteliregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_commoninteliregistry_username }}
        container-registry-password: ${{ secrets.acr_commoninteliregistry_password }}
        secret-name: commonaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: common-apps
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          commoninteliregistry.azurecr.io/commonaks:${{ github.sha }}
        imagepullsecrets: |
          commonaksdockerauth
